export const ImageKeys = {
  LLAMA_1: 'llama-1',
  LLAMA_2: 'llama-2',
  LLAMA_3: 'llama-3',
  LLAMA_4: 'llama-4',
  LLAMA_EAT_1: 'llama-eat-1',
  LLAMA_EAT_2: 'llama-eat-2',
  LLAMA_EAT_3: 'llama-eat-3',
  LLAMA_EAT_4: 'llama-eat-4',
  HOURGLASS: 'hourglass',
  GRASS: 'grass',
  SPIT: 'spit',
  MOUNTAIN: 'mountain',
  CROWN: 'crown',
  BORDER_TOP_LEFT: 'border-top-left',
  BORDER_BOTTOM_LEFT: 'border-bottom-left',
  BORDER_TOP_RIGHT: 'border-top-right',
  BORDER_BOTTOM_RIGHT: 'border-bottom-right',
  BORDER_HORIZONTAL: 'border-horizontal',
  BORDER_VERTICAL: 'border-vertical',
  BLANK_BUTTON: 'blank-button',
  BLANK_BUTTON_PRESSED: 'blank-button-pressed',
  DELETE_BUTTON_1: 'delete-button-1',
  DELETE_BUTTON_2: 'delete-button-2',
}

export const AudioKeys = {
  ATTACK_1: 'attack1',
  ATTACK_2: 'attack2',
  ATTACK_3: 'attack3',
  DEATH: 'death',
  WALK: 'walk',
  NEW_TURN: 'new-turn',
  PLAYER_DEFEATED: 'player-defeated',
  PLAYER_JOINED_LOBBY: 'player-defeated',
  VICTORY_MUSIC: 'victory-music',
  CLICK: 'click',
  SPIT: 'spit',
  MATURE: 'mature',
}

export const ALL_AUDIO_KEYS = [
  AudioKeys.ATTACK_1,
  AudioKeys.ATTACK_2,
  AudioKeys.ATTACK_3,
  AudioKeys.DEATH,
  AudioKeys.WALK,
  AudioKeys.NEW_TURN,
  AudioKeys.PLAYER_DEFEATED,
  AudioKeys.PLAYER_JOINED_LOBBY,
  AudioKeys.VICTORY_MUSIC,
  AudioKeys.CLICK,
  AudioKeys.SPIT,
  AudioKeys.MATURE,
]
